### ISSUE TITLE
Reduce summarization time for larger documents

### ISSUE THREAD

**Issue by aadarsh-ram** [aadarsh-ram/my-gpt-backend#10]
Currently, GPU offloading is done for faster inference. Check if there are other ways to improve performance.
- Change LLM
- Hybrid (Extractive + Abstractive)
- Use MLC-LLM for pre-compilation and inference

**Comment by aadarsh-ram** [comment]
"n_batch" allows for GPU batch processing, and speeds up summarization significantly.

**Comment by aerial-ace1** [comment]
L
