### ISSUE TITLE
Slider to control number of chunk inputs

### ISSUE THREAD

**Issue by FrozenWolf-Cyber** [aadarsh-ram/my-gpt-backend#14]
Control inference speed by controlling number of retrieved input chunks: say 2, 4, 8 - fast, normal, accurate

**Comment by aadarsh-ram** [comment]
By default, chunk size is currently 200 with k = 8

**Comment by aerial-ace1** [comment]
L

**Comment by FrozenWolf-Cyber** [comment]
L
