### ISSUE TITLE
Grammar Checks (Frontend)

### ISSUE THREAD

**Issue by aadarsh-ram** [aadarsh-ram/my-gpt-backend#5]
Create a page for grammar checks and reformatting. Need a design for that page.

**Comment by aerial-ace1** [comment]
This JS Module seems to be a fine differ
https://github.com/kpdecker/jsdiff

**Comment by aadarsh-ram** [comment]
Probably just need to bring a grammarly-like UI

**Comment by aadarsh-ram** [comment]
Closing as feature is implemented in frontend
